@startuml
start

:Accès au site;
:Navigation libre;
:Recherche de produit;

while (Produit trouvé ?) is (Non)
  :Changer les filtres;
  :Voir les boutiques et produits;
endwhile (Oui)

:Voir les détails;

if (Souhaite réserver ?) then (Oui)
  while (Connecté ?) is (Non)
    :Redirection vers Connexion ou Création de compte;
  endwhile (Oui)

  :Réserver le produit;
  :Confirmation commerçant;
  if (Produit confirmé ?) then (Oui)
    :Valider la transaction;
  else (Non)
    :Produit indisponible;
  endif
else (Non)
  :Ajouter aux favoris (si connecté);
endif

stop
@enduml
