import type { Metadata } from "next";

// Import global styles
import "./globals.css";

// Import components
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";
import { CartProvider } from "@/components/context/CartContext";
import FloatingCart from "@/components/cart/floatingCart";

// Define metadata
export const metadata: Metadata = {
  title: "Easy-Place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="background-gradient min-h-screen">
        <Header />
        <CartProvider>
          {children}
          <FloatingCart />
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
